######################################################################
# Automatically generated by qmake (2.01a) ??? ??? 21 14:41:18 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ui_mainwindow.h
